### ISSUE TITLE
X_FORWARDED_SUPPORT doesn't work on server nodes.

### ISSUE THREAD

**Issue by Kuinox** [openseedbox/openseedbox#94] opened 2022-10-14 17:17 UTC
With the docker compose I have setup the whole thing.
I was able to set `X_FORWARDED_SUPPORT` on the front server so it works through my reverse proxy (caddy).  
For the server, I set up the same env variable, but it doesn't work:  
![image](https://user-images.githubusercontent.com/18743295/195904476-38b806e5-261e-482b-a86c-06e99999c5ba.png)
![image](https://user-images.githubusercontent.com/18743295/195904527-cbd62b9f-ae1e-4f87-bd87-ced7547d9abf.png)

**Comment by xabolcs** [comment] 2022-10-14 17:29
" ... on server nodes"? :thinking: 

So the frontend works nicely? (because of commit 5955be300e97cb61619d264ddf7b52f805f85521) :slightly_smiling_face:

**Comment by Kuinox** [comment] 2022-10-14 17:39
Yes, the frontend work without issue, but the download links target the worker node server.

**Comment by xabolcs** [comment] 2022-10-14 17:48
I see!

Let me port that commit to `openseedbox-server`, later tonight.

**Comment by Kuinox** [comment] 2022-10-14 19:56
thanks !

**Comment by xabolcs** [comment] 2022-10-14 22:05
I forget about the backend when I fixed #91.
Let me close this as a duplicate of the just reopened #91.

**Closed by xabolcs** 2022-10-14 22:05 UTC
Labels: duplicate
