### ISSUE TITLE
Docker container images are broken - missing Siena modules

### ISSUE THREAD

**Issue by gregorkistler** [openseedbox/openseedbox#52] opened 2017-04-30 11:20 UTC
Since the last update of the Docker images mentioned in the readme 10 days ago they can´t be used anymore.
Both container images openseedbox/client as well as openseedbox/server will start but the Nginx in each case only delivers a 502 bad gateway message.

Reason: missing Siena modules

As you can see in the build details of the [client](https://hub.docker.com/r/openseedbox/client/builds/bwkp9jtbhuxay8bgeuv8dsj/) and [server](https://hub.docker.com/r/openseedbox/server/builds/bc49ittccuywq3kieew6yrw/):

> WARNING:
> These dependencies are missing, your application may not work properly (use --verbose for details),
>~
>~	play->siena 2.0.7

as well as the Docker logs:

>09:40:35,929 INFO  ~ Precompiling ...
09:40:37,766 ERROR ~ 
@73okj3kaa
Cannot start in PROD mode with errors
Compilation error (In /app/com/openseedbox/models/ModelBase.java around line 14)
The file /app/com/openseedbox/models/ModelBase.java could not be compiled. Error raised is : EnhancedModel cannot be resolved to a type
play.exceptions.CompilationException: EnhancedModel cannot be resolved to a type
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:246)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:676)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:520)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:282)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:426)
	at play.Play.preCompile(Play.java:603)
	at play.Play.init(Play.java:307)
	at play.server.Server.main(Server.java:162)

Older Play! Framework binaries can´t retrieve modules from the playContributedModules repository because the URL changed some time ago from http://www.playframework.org/modules to https://www.playframework.com/modules
Even if you correct the URL it still won´t work - also described [here](https://www.bountysource.com/issues/43478415-problem-installing-module).

To work around the issue the Siena module needs to be [downloaded](https://www.playframework.com/modules/siena-2.0.7.zip) and unzipped into the Play! Framework module directory.
As soon as it´s in place, dependencies will be resolved successfully again without any further changes.

Second bug in one of the container images (client to be more specific) is the one fixed with 02a23b97bc6d239e5c2691897d892a2f1e26a507.

@xabolcs is it something only @erindru can fix or do you also have permission to push to the Docker Hub repo?

**Comment by xabolcs** [comment] 2017-04-30 12:44
Yeah ... www.playframework.com updated it's https configuration and old urllibs die.
I faced with too.

The related issue what you also found is playframework/play1#1126.

The workaround for `Dockerfile` doesn't helps setting up the development environment.

**Comment by gregorkistler** [comment] 2017-04-30 13:06
True, didn´t notice that you posted the last comment, was more busy with the content of it :)

I personally work around the issue that way since at least one year maybe even two as it never worked out of the box for me.
Always had a non-resolvable Siena module dependency issue.

Let´s see what the guys over at Play! Framework will do.

**Comment by xabolcs** [comment] 2017-04-30 13:13
Fix is coming. :+1:

**Comment by xabolcs** [comment] 2017-04-30 20:24
Workaround commit 58a15b8fa0f5a016ebb824eb74f930db10507f6c is pushed.
It's time to update Docker Hub.

**Comment by xabolcs** [comment] 2017-04-30 20:29
@erindru , please update images at Docker Hub, thanks!

**Comment by gregorkistler** [comment] 2017-05-01 10:46
Guess the dependency cleanup in the backend with commit https://github.com/openseedbox/openseedbox-server/commit/3684cad1a8837c7df41e8d8d679f929dcec0fb3d was a little bit too much :)

>12:14:23,900 INFO  ~ Precompiling ...
12:14:25,623 ERROR ~ 
>
> @73p24golk
Cannot start in PROD mode with errors
>
>Compilation error (In {module:openseedbox-common}/app/com/openseedbox/backend/NodeStatus.java around line 3)
The file {module:openseedbox-common}/app/com/openseedbox/backend/NodeStatus.java could not be compiled. Error raised is : siena.embed.EmbeddedMap cannot be resolved
>
>play.exceptions.CompilationException: siena.embed.EmbeddedMap cannot be resolved
...

Frontend looks good now.

**Comment by xabolcs** [comment] 2017-05-02 00:57
All Docker images should be functional!

**Comment by gregorkistler** [comment] 2017-05-02 18:58
I´ve pulled the latest images from Docker Hub a couple of minutes ago but the server image still doesn´t work correctly.
Siena module dependency was fixed so we could close this one here if needed and create a new one based on the following error:

```
18:01:01,384 ERROR ~ 

@73pbkpf8a
Cannot start in PROD mode with errors

Compilation error (In /app/com/openseedbox/backend/transmission/TransmissionBackend.java around line 158)
The file /app/com/openseedbox/backend/transmission/TransmissionBackend.java could not be compiled. Error raised is : The method encodeBase64String(byte[]) is undefined for the type Base64

play.exceptions.CompilationException: The method encodeBase64String(byte[]) is undefined for the type Base64
	at play.classloading.ApplicationCompiler$2.acceptResult(ApplicationCompiler.java:246)
	at org.eclipse.jdt.internal.compiler.Compiler.handleInternalException(Compiler.java:676)
	at org.eclipse.jdt.internal.compiler.Compiler.compile(Compiler.java:520)
	at play.classloading.ApplicationCompiler.compile(ApplicationCompiler.java:282)
	at play.classloading.ApplicationClassloader.getAllClasses(ApplicationClassloader.java:426)
	at play.Play.preCompile(Play.java:603)
	at play.Play.init(Play.java:307)
	at play.server.Server.main(Server.java:162)
```

Issue #14 was about the same and provides a solution by adding `- commons-codec -> commons-codec 1.7` back into the dependencies.yml
The odd thing about the error is that I had it once during the last few days but currently cannot reproduce it.
Code from the repo works solid on different hosts and docker-compose setups.

Java version related?
The Docker images uses OpenJDK 1.6.0_38
I´ve successfully tested it with 1.6.0_41, 1.7.0_121 and 1.8.0_111 as well as 1.8.0_121

**Comment by xabolcs** [comment] 2017-05-02 19:33
Docker sucks and I'm noob. :trollface: 
How do you refresh / rebuild your Docker containers?

This `common-codec` stuff is caused by the siena [dependencies](https://www.playframework.com/documentation/1.2.x/dependency#Transitivedependencies) in `openseedbox-common` which should be fixed by the latest commit openseedbox/openseedbox-common@020990fa574734e131d745e8d3a467c8abb58874.

**Comment by xabolcs** [comment] 2017-05-02 19:39
Linked `openseedbox/server` automated build to `openseedbox/client` (and retriggered), hope this helps.

```
Link your Automated Build to another Docker Hub repository, and when that repository is updated, it will automatically trigger a rebuild of this Automated Build.
```

**Comment by gregorkistler** [comment] 2017-05-02 19:55
I actually just delete the related container and images and use docker run to pull it completely from Docker Hub again.

One of the latest to builds fixed the issue :)
Backend runs as expected again.

**Comment by xabolcs** [comment] 2017-05-02 20:01
`docker pull && docker run` is my new friend. :)

Thanks for the feedback.

**Closed by xabolcs** 2017-05-02 20:01 UTC
